### PR TITLE
Worked on translations

### PR DESCRIPTION
**Pull request by HanSolo72**
I extended many untranslated php files to work with the language files. Also I changed all the German translation identifiers to English and changed it accordingly in all translation files. Before there was a mix of English and German. Now it should be easier for non German speakers to contribute translations.

### CODE REVIEW

**Comment by HanSolo72** [comment]
Found a little mistake in the translation

**Review by ThmsD — COMMENTED** [review]
One thing I noticed, for example.
In English it's called 'address', not 'adress'.

**Comment by HanSolo72** [comment]
> One thing I noticed, for example. In English it's called 'address', not 'adress'.

Thank you, I know that but I haven't seen it. I change it this afternoon and upload it again.

**Comment by HanSolo72** [comment]
I make a new pull request.

**Pull request closed without merging**
