### PR TITLE
Add charge_port_door_open to web commands

### PR DESCRIPTION
**Pull request by ThmsD**
Closes bassmaster187/TeslaLogger#774

### CODE REVIEW

**Comment by superfloh247** [comment]
no

there is a reason we do not support "dangerous" commands

**Comment by ThmsD** [comment]
Oh, okay. I didn't know that.
Could you please explain why charge port open is a "dangerous" command?
I just want to understand it.

**Comment by Adminius** [comment]
Let's assume: some body can hack your SmartHome /NFC and unlock chargeport and ans steel your charging cable...

Dangerous commands: open car/frunk/trunk/windows/charge port/sun roof...

**Comment by bassmaster187** [comment]
the question is:
Shouldn't we make it possible to open the charge_port, by enable it in config file (not ui, that's too dangerous). 
And the URL is combined with "i really know what i do" and with the tasker token id, so the user have to read the docs and the risc. 
e.g:
http://localhost:5000/command/charge_port_door_open/I_really_know_what_I_do/[tasker_token_id]

**Comment by Adminius** [comment]
the original issue is: unlock cable via NFC/TL and not only open charge port...
OpenCharge port is not so dangerous as unlock.
but /I_really_know_what_I_do/[tasker_token_id]] sounds good :)

**Pull request closed without merging**
