### PR TITLE
Added 1045 US superchargers

### PR DESCRIPTION
**Pull request by HanSolo72**
Source: supercharge.info at 1. May 2022

### CODE REVIEW

**Comment by Adminius** [comment]
Hi @HanSolo72, thank you!
I'm not sure about deleted SuCs. Supercharge.info doesn't use same names as Tesla uses. I used names from Tesla side to (mostly) catch same name as displayed in car navigation and on tesla.com/findus
Also, as supercharge.info information useful as a "placeholder", but in the past I had a lot of troubles, because location doesn't match real charging location sended by car (teslalogger.de/map.php)

**Comment by HanSolo72** [comment]
I needed a list of SC's like supercharge.info proviedes. Tesla has a [list](https://www.tesla.com/findus/list/superchargers/United+States), but without coordinates.

Will you say that Teslalogger matches the superchargers by name only? What happens if I charge at a supercharger that is not in the geofenes.csv list?

I only could invest some hours of work and write a vb script that scans this list and opens every link and read the coordinates from the html code and write that information into a text file. That would gave the benefit to create a current list of superchargers from the best source. I already done things like that and I will think about it.

**Comment by Adminius** [comment]
Coordinates on Tesla Site are worse than on supercharge.info... 
The only true location if somebody already charged there and shared it to teslalogger.de/map.php
That's why some location still not in the list (I cloud also get all locations from one of the sources... )
That's why i did **manual** search for all "blue" dot's on the map, than googled for location or compared it to tesla-map than added it to geofence :/ 
Tesla Findus coordinates are sometimes hundreds of meters away from the real location... that's why in the past (we did some scripting to add EU locations before) a lot of locations didn't match (after some users charged there) and we corrected this locations manually :/ 

So, you can try to add scripted locations, but do not delete existing, because they are good and added by myself manually

**Comment by Adminius** [comment]
another question: last column means radius, but it seams like in your PR you used stall amount?

**Comment by Adminius** [comment]
Example, were supercharge.info position is to far away from the real SuC:
(green circle is position from supercharge.info)
https://teslalogger.de/map.php?lat=49.160465&lng=11.26101

**Comment by HanSolo72** [comment]
> another question: last column means radius, but it seams like in your PR you used stall amount?

I just multiplied the amount of stalls by 1.5, so bigger superchargers gets a bigger radius. Without knowledge about the situation on the specific site I saw no other way.

I think it's better to have not so accurate supercharger data than no supercharger data. If a Teslalogger user who regularly uses some superchargers has to adjust it on his own like you did it with Hilpoltstein.

**Comment by Adminius** [comment]
> I just multiplied the amount of stalls by 1.5

than leave it without radius, default is 50 and good.




> I think it's better to have not so accurate supercharger data than no supercharger data.

agree. But do not remove exiting entries, because these are ok and manually added by my self... it was already a lot of work

**Comment by HanSolo72** [comment]
> than leave it without radius, default is 50 and good.

Ok, didn't know about the default value.

> agree. But do not remove exiting entries, because these are ok and manually added by my self... it was already a lot of work

I didn't remove anything. It only looks like because I sorted them all alphabetically.

I delete it and make a new pull request without radius and I and put the new ones at the end. Then it shouldn't look like I deleted anything.

**Comment by Adminius** [comment]
> I didn't remove anything.

ok, you right. but some new are "equal" to old entries:

This was my old entry that still exists
https://github.com/bassmaster187/TeslaLogger/pull/811/commits/0b4987b811ad654c1a587e8cb8c753d1bb247c4a#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471L843

and this one is probably the same with a littlie bit different location:
https://github.com/bassmaster187/TeslaLogger/pull/811/commits/0b4987b811ad654c1a587e8cb8c753d1bb247c4a#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471R976

So, I would say:
- Delete radius and leave it blank (=default to 50m)
- delete new duplicates 

and it can be merged

**Comment by Adminius** [comment]
> > I didn't remove anything.
> 
> ok, you are right. but some new are "equal" to old entries:
> 
> This was my old entry that still exists [0b4987b#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471L843](https://github.com/bassmaster187/TeslaLogger/commit/0b4987b811ad654c1a587e8cb8c753d1bb247c4a#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471L843)
> 
> and this one is probably the same with a littlie bit different location: [0b4987b#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471R976](https://github.com/bassmaster187/TeslaLogger/commit/0b4987b811ad654c1a587e8cb8c753d1bb247c4a#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471R976)
> 
> So, I would say:
> 
> * Delete radius and leave it blank (=default to 50m)
> * delete new duplicates
> 
> and it can be merged

**Comment by HanSolo72** [comment]
> This was my old entry that still exists [0b4987b#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471L843](https://github.com/bassmaster187/TeslaLogger/commit/0b4987b811ad654c1a587e8cb8c753d1bb247c4a#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471L843)
> 
> and this one is probably the same with a littlie bit different location: [0b4987b#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471R976](https://github.com/bassmaster187/TeslaLogger/commit/0b4987b811ad654c1a587e8cb8c753d1bb247c4a#diff-8e2f41487064d307611dc42fb71cddf01717ed5002e34cb9369f1863c769c471R976)

Your Buttonwillow line is actually a supercharger in Bakersfield, that's the reason they was both in my changes, because I deleted the doubles by coordinates in Excel. I will make a pully request for that one too.

**Comment by HanSolo72** [comment]
Another question before I add those over 1000 superchargers:
How important is that the supercharger name matches the official name at the Tesla website?

As example, the SC in Morongo Trail's name in supercharge.info is:
Cabazon - Morongo Trail, CA (supercharge.info)
Cabazon, CA - Morongo Trail [(Tesla website)](https://www.tesla.com/findus/location/supercharger/CabazonCASupercharger2)

**Comment by Adminius** [comment]
both names are ok. It's important to have NO "," in the name. 
Some names in superchage.info are completely different (no similarity to tesla web cite), that is not OK, because it can be confusing for user.

I don't know witch licence superchage.info has... is it allowed to use their data?

**Comment by bassmaster187** [comment]
@HanSolo72 : could you please check the license of supercharge.info data?

**Comment by HanSolo72** [comment]
> @HanSolo72 : could you please check the license of supercharge.info data?

They don't write anything about licensing on their [about site](https://supercharge.info/about) and they don't answer my [question in the forum](https://forum.supercharge.info/t/is-the-data-under-any-licencse/2038).

**Comment by Adminius** [comment]
I would say: Public Domiain:
https://forum.supercharge.info/t/downloading-supercharger-data/215

**Comment by HanSolo72** [comment]
I make a new pull request with the US Superchargers in a few days with the changes discussed here.

**Pull request closed without merging**
